apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngvol
spec:
  selector:
    matchLabels:
      app: fuse-test
  replicas: 1
  template:
    metadata:
      labels:
        app: fuse-test
    spec:
      containers:
      - name: fuser
        image: nginx:alpine
        volumeMounts:
          - name: v3io
            mountPath: /v3io
      volumes:
        - name: v3io
          flexVolume:
            driver: "v3io/fuse"
            secretRef:
              name: v3io-user-fuse
            options:
              container: bigdata
